### PR TITLE
Fix background and alignment of node details section

### LINKED ISSUE #140: Node section background lacks background colour and planet size is wrong in mobile

### PR DESCRIPTION
**Pull request by alexandercyu**
Fixes #140
- Fix background and planet image of node details section
- Fix alignment of text of node details section

### CODE REVIEW

**Review by mishaschwartz — CHANGES_REQUESTED** [review]
Background is now broken when screen width is `md`

image

**Comment by alexandercyu** [comment]
> Background is now broken when screen width is `md`
> 
> image

Fixed background for md sizes. Also added a margin for node details at md size.

**Review by ShrutiK100 — CHANGES_REQUESTED** [review]
The gap between heading and body is more than 30px, email and version also seems more than 30px. Needs to be a consitent 30px gap between all section elements
Screenshot 2024-05-30 at 11 14 38 AM

**Comment by alexandercyu** [comment]
> The gap between heading and body is more than 30px, email and version also seems more than 30px. Needs to be a consitent 30px gap between all section elements Screenshot 2024-05-30 at 11 14 38 AM

I mentioned this in Figma.  The space between email and version is 32px in desktop and I asked if it could be changed in mobile.

I've now changed it to 30px.

**Review by ShrutiK100 — CHANGES_REQUESTED** [review]
Still don't see the 30px gap 
Screenshot 2024-05-30 at 11 42 18 AM
Needs to be consistent 30px
Screenshot 2024-05-30 at 11 14 38 AM

**Comment by alexandercyu** [comment]
> Still don't see the 30px gap Screenshot 2024-05-30 at 11 42 18 AM Needs to be consistent 30px Screenshot 2024-05-30 at 11 14 38 AM

Screenshot 2024-05-30 at 11 57 05 AM (2)
Screenshot 2024-05-30 at 11 50 39 AM (2)
Screenshot 2024-05-30 at 11 51 48 AM (2)
Screenshot 2024-05-30 at 11 58 04 AM (2)

**Review by mishaschwartz — COMMENTED** [review]
The margins look different because some of the child elements also have margins that get added to the 30px margin from the `.node-main-info` elements

**Comment by alexandercyu** [comment]
> The margins look different because some of the child elements also have margins that get added to the 30px margin from the `.node-main-info` elements

Removed the default margins on the h2 and p elements.

**Review by ShrutiK100 — CHANGES_REQUESTED** [review]
Alignment looks good
Version is Caption • Regular • 14|Auto . Seems like its body1

**Comment by alexandercyu** [comment]
> Alignment looks good Version is Caption • Regular • 14|Auto . Seems like its body1

Changed to caption font type.

**Review by ShrutiK100 — CHANGES_REQUESTED** [review]
Version font change might have affected alignment on browser site. On browser email and version should align horizontally with the components on left hand side.
Screenshot 2024-06-03 at 11 48 06 AM

**Comment by alexandercyu** [comment]
> Version font change might have affected alignment on browser site. On browser email and version should align horizontally with the components on left hand side. Screenshot 2024-06-03 at 11 48 06 AM

Screenshot 2024-06-03 at 11 53 02 AM (3)


This seems to be aligned like the design.  Am I missing something?

**Comment by alexandercyu** [comment]
Aligned the email with the description text.

**Review by mishaschwartz — APPROVED** [review]

**Review by ShrutiK100 — APPROVED** [review]
Looks good!

**Pull request merged**
