### PR TITLE
Created mobile version of About page

### PR DESCRIPTION
**Pull request by alexandercyu**
NOTE: h3 and h6 header tags still have a margin below them that have been taken out in previously made branches.  Didn't want to duplicate the change here.  Once those have been merged, it can be pulled into this branch.

NOTE: Button in FAQ section has a different size in the prototype than what is defined in the design.  It is 99px wide instead of the standard 108px for a medium button or 75px for a small button.  Is there a new design for this FAQ button?

- Added mobile versions of titles and content sections

### CODE REVIEW

**Review by mishaschwartz — CHANGES_REQUESTED** [review]
Sections that don't match figma design:

- mission
- our story
- DACCS

The "Executive" and "Scientific" text is too small on `md` size.

**Review by mishaschwartz — CHANGES_REQUESTED** [review]
From https://github.com/DACCS-Climate/marble-website/pull/125#pullrequestreview-2056033197:

> The "Executive" and "Scientific" text is too small on md size.

**Comment by ShrutiK100** [comment]
> NOTE: h3 and h6 header tags still have a margin below them that have been taken out in previously made branches. Didn't want to duplicate the change here. Once those have been merged, it can be pulled into this branch.
> 
> NOTE: Button in FAQ section has a different size in the prototype than what is defined in the design. It is 99px wide instead of the standard 108px for a medium button or 75px for a small button. Is there a new design for this FAQ button?
> 
> * Added mobile versions of titles and content sections

Not sure which component you are referring to. If you are referring to the arrow it will be same as the browser one

**Comment by alexandercyu** [comment]
> > NOTE: h3 and h6 header tags still have a margin below them that have been taken out in previously made branches. Didn't want to duplicate the change here. Once those have been merged, it can be pulled into this branch.
> > NOTE: Button in FAQ section has a different size in the prototype than what is defined in the design. It is 99px wide instead of the standard 108px for a medium button or 75px for a small button. Is there a new design for this FAQ button?
> > 
> > * Added mobile versions of titles and content sections
> 
> Not sure which component you are referring to. If you are referring to the arrow it will be same as the browser one

It's this one:
Screenshot 2024-05-15 at 9 58 12 AM (2)Crop


It has a different size than the other buttons that have already been created in the system.
Screenshot 2024-05-15 at 9 57 46 AM (2)Crop
Screenshot 2024-05-15 at 9 56 58 AM (2)Crop

**Comment by ShrutiK100** [comment]
> > > NOTE: h3 and h6 header tags still have a margin below them that have been taken out in previously made branches. Didn't want to duplicate the change here. Once those have been merged, it can be pulled into this branch.
> > > NOTE: Button in FAQ section has a different size in the prototype than what is defined in the design. It is 99px wide instead of the standard 108px for a medium button or 75px for a small button. Is there a new design for this FAQ button?
> > > 
> > > * Added mobile versions of titles and content sections
> > 
> > 
> > Not sure which component you are referring to. If you are referring to the arrow it will be same as the browser one
> 
> It's this one: Screenshot 2024-05-15 at 9 58 12 AM (2)Crop
> 
> It has a different size than the other buttons that have already been created in the system. Screenshot 2024-05-15 at 9 57 46 AM (2)Crop Screenshot 2024-05-15 at 9 56 58 AM (2)Crop

All buttons on browser are Regular/Default and all buttons on mobile design are Medium/Default

**Review by ShrutiK100 — CHANGES_REQUESTED** [review]
All buttons in mobile design are Medium/Default(defined in design system). 
Useful Links section needs to fall under feedback section, 
Feedback section has subsection-forum and feedback, Forum section is missing.
All sections should have a 50px gap, 30px under all headings, 20px under all subheading and 20px between body and the buttons.

**Comment by alexandercyu** [comment]
> All buttons in mobile design are Medium/Default(defined in design system). Useful Links section needs to fall under feedback section, Feedback section has subsection-forum and feedback, Forum section is missing. All sections should have a 50px gap, 30px under all headings, 20px under all subheading and 20px between body and the buttons.

Wasn't the forum section moved to the Community menu item?

**Comment by alexandercyu** [comment]
> From [#125 (review)](https://github.com/DACCS-Climate/marble-website/pull/125#pullrequestreview-2056033197):
> 
> > The "Executive" and "Scientific" text is too small on md size.

Changed the breakpoint of the "Executive" and "Scientific" text.

**Review by mishaschwartz — CHANGES_REQUESTED** [review]
Please put the underline under the committee options back

**Comment by alexandercyu** [comment]
> Please put the underline under the committee options back

I'm not sure what you mean.  Do you mean the Executive-Scientific buttons? It was never gone.

Screenshot 2024-05-17 at 9 44 16 AM (2)Crop Small
Screenshot 2024-05-17 at 9 44 09 AM (2)Crop Large

**Review by mishaschwartz — APPROVED** [review]

**Comment by alexandercyu** [comment]
> > > > NOTE: h3 and h6 header tags still have a margin below them that have been taken out in previously made branches. Didn't want to duplicate the change here. Once those have been merged, it can be pulled into this branch.
> > > > NOTE: Button in FAQ section has a different size in the prototype than what is defined in the design. It is 99px wide instead of the standard 108px for a medium button or 75px for a small button. Is there a new design for this FAQ button?
> > > > 
> > > > * Added mobile versions of titles and content sections
> > > 
> > > 
> > > Not sure which component you are referring to. If you are referring to the arrow it will be same as the browser one
> > 
> > 
> > It's this one: Screenshot 2024-05-15 at 9 58 12 AM (2)Crop
> > It has a different size than the other buttons that have already been created in the system. Screenshot 2024-05-15 at 9 57 46 AM (2)Crop Screenshot 2024-05-15 at 9 56 58 AM (2)Crop
> 
> All buttons on browser are Regular/Default and all buttons on mobile design are Medium/Default

Made all buttons on desktop regular size and all buttons on mobile medium size.

**Review by ShrutiK100 — CHANGES_REQUESTED** [review]
Add 30px under heading "Feedback"
Screenshot 2024-05-17 at 3 49 01 PM

Add 30px un all 3 headings
Screenshot 2024-05-17 at 3 47 33 PM

check the gap between useful links and connect with us
Screenshot 2024-05-17 at 3 45 35 PM

Connect with us is not aligned as in design
Screenshot 2024-05-17 at 3 45 11 PM

**Comment by alexandercyu** [comment]
> Add 30px under heading "Feedback" Screenshot 2024-05-17 at 3 49 01 PM
> 
> Add 30px un all 3 headings Screenshot 2024-05-17 at 3 47 33 PM
> 
> check the gap between useful links and connect with us Screenshot 2024-05-17 at 3 45 35 PM
> 
> Connect with us is not aligned as in design Screenshot 2024-05-17 at 3 45 11 PM

> NOTE: h3 and h6 header tags still have a margin below them that have been taken out in previously made branches. Didn't want to duplicate the change here. Once those have been merged, it can be pulled into this branch.


> All FAQ section and Feedback section changes have been made in marble-mobile-home.

**Pull request merged**
